services:
  app:
    image: e-paper-dashboard:dev
    # user: "${UID}:${GID}" set to match host user
    ports:
      - "8128:8128"
      - "8129:8129"
    environment:
      - CLIENT_URL=http://192.168.2.187:8128
      - STATE_SIGNING_KEY=YourSecureRandomKeyHere32BytesMinimum!
      - SUPERUSER_USERNAME=admin
      - SUPERUSER_PASSWORD=admin
      - TZ=Europe/Berlin
    volumes:
      - appdata:/data
  
  home-assistant:
    image: homeassistant/home-assistant:latest
    ports:
      # Expose home-assistant port on host interface
      - 8123:8123

volumes:
  appdata:
